def print_hangman(guessesLeft)
    if guessesLeft == 7:
        print('_______')
        print('|            |')
        print('|          (_)')
        print('|')
        print('|')
        print('|')
    if guessesLeft == 6:
        print('_______')
        print('|           |')
        print('|         (_)')
        print('|           | ')
        print('|           |')
        print('|')
    if guessesLeft == 5:
        print('_______')
        print('|           |')
        print('|         (_)')
        print('|         /| ')
        print('|           |')
        print('|')
    if guessesLeft == 4:
        print('_______')
        print('|           |')
        print('|         (_)')
        print('|         /|\ ')
        print('|           |')
        print('|')
    if guessesLeft == 3:
        print('_______')
        print('|           |')
        print('|         (_)')
        print('|         /|\ ')
        print('|           |')
        print('|          /')
    if guessesLeft == 2:
        print('_______')
        print('|           |')
        print('|         (_)')
        print('|         /|\ ')
        print('|           |')
        print('|          /\ ')
    if guessesLeft == 1:
        print('_______')
        print('|           |')
        print('|         (_)')
        print('|         /|\ ')
        print('|           |')
        print('|        _/\ ')
    else:
        print('_______')
        print('|           |')
        print('|         (_)')
        print('|         /|\ ')
        print('|           |')
        print('|        _/\_')
